python-hyper/hyperframe

- .gitignore
This PR adds `.cache` directory to `.gitignore`.
It seems to be created by pytest.
> ignore cache

- hyperframe/frame.py
- test/test_hyperframe.py
Explicitly setting `stream_id = 0` for frames without a stream association is a bit verbose.
This PR removes this by defaulting the `stream_id` to `0`. 
Since the mixin classes require a `stream_id` argument for `init`, I had to keep it. Is there a cleaner solution?
> simplify stream association init

- hyperframe/frame.py
- test/test_hyperframe.py
similar to #7
This PR allows us to pass in settings during SettingsFrame initialization - which makes it a bit less verbose.
> Settings frame init

- hyperframe/frame.py
- test/test_hyperframe.py
`Frame.parse_frame_header` should throw a ValueError if the frame type is unknown, throwing a KeyError feels weird.
> Add stricter frame parsing

- hyperframe/frame.py
- test/test_hyperframe.py
This PR supersedes #7 and allows setting all frame attributes via constructors. The only unusual thing in this PR might be that mixin arguments (and `flags`) are provided as keyword arguments only. This has been done as the combination of mixins and positional arguments tends to be quite confusing.
An alternative would be to repeat all arguments in each constructor, but I found this to be quite verbose.
> Allow attributes to be set via constructors

- hyperframe/flags.py
- hyperframe/frame.py
- test/test_flags.py
- test/test_frames.py
- test/test_hyperframe.py
We had slightly different flag names in our old mitmproxy code (e.g. https://github.com/mitmproxy/netlib/commit/d7ada2f6b6a3b4dc2525c12c2ae24bf3d5e043b4), which went unnoticed because hyperframe just swallowed invalid flags. I personally think it would be nice to have some validation here. If you want to keep things simpler, that'd be okay as well as we found our offenders now. :wink: 
Cheers,
Max
> add flag validation

- test_requirements.txt
Python 3.5 builds were failing for no good reason: turned out to be test dependencies.
> Pin test dependency versions.

- hyperframe/frame.py
- test/test_frames.py
When parsing frames, it would be helpful to know what the body length of the frame is (e.g. for enforcing SETTINGS_MAX_FRAME_SIZE). This records that information on all frame types.
> Add body_len to all parsed frames.

- HISTORY.rst
- docs/source/api.rst
- hyperframe/exceptions.py
- hyperframe/frame.py
- test/test_frames.py
This allows users to introspect the unknown frame and potentially to skip it for frame parsing.
> Add new UnknownFrameError

- docs/source/api.rst
- hyperframe/exceptions.py
- hyperframe/frame.py
- test/test_frames.py
This is required for python-hyper/hyper-h2#73.
/cc @mhils to confirm I didn't break anything needed there.
> Reject padded frames with invalid padding lengths.

- hyperframe/frame.py
- test/test_frames.py
Resolves a bug in hyperframe 3.0.0 where zero-length data frames with no padding raise InvalidPaddingError. This error should generally be impossible to raise in a situation where there is no padding.
> Don't raise InvalidPaddingError on unpadded 0 length frames

- hyperframe/frame.py
- test/test_frames.py
`None` does not play well with `int(None)` and `None | 0x0`.
This might induce a change in hyper-h2.
> fix default values due to incompatible conversions

- HISTORY.rst
- hyperframe/frame.py
- test/test_frames.py
Ping frames must have exactly 8 bytes of data.
> Reject short PING frames.

- hyperframe/frame.py
- test/test_frames.py
fixes #29 
Not sure if the doc-strings actually work - any ideas to clearly mark the deprecation?
I also played with the idea of printing a warning to stderr or so, but that is a bit too much I think.
> rename and unify setting variable names

- HISTORY.rst
- hyperframe/frame.py
> Throw InvalidFrameError, not ValueError

- HISTORY.rst
- hyperframe/frame.py
- test/test_frames.py
> Don't let ALT_SVC fail without InvalidFrameError

- hyperframe/frame.py
As per [Twitter](https://twitter.com/lukasaoz/status/765820112893009920), small PR to fix the `AltSvcFrame` `stream_association` to be `either`, instead of the incorrect `both`. The logic works correctly with either value, regardless.
> Fix AltSvcFrame `stream_association`

- hyperframe/frame.py
Hello, I am here to provide some ideas of potential optimizations to Frame parsing and serialization at the suggestion of @Lukasa .  All of the following optimizations have exactly the same behavior (given a few axioms) but are much faster than their counterparts.
These optimizations are on the microsecond level, but because this is a low-level library intended to be used within tight loops every cycle counts. Luckily these optimizations (in my opinion) do not degrade readability and if they do could be justified with a single comment.
All optimizations are tested using the `timeit` module, if you would like you may test them yourself and see the results. I have categorized the optimizations into *Less aggressive* and *Aggressive*.
If this sort of optimization is welcome, I would also …
> Optimization of Frame parsing/serialization.

- hyperframe/frame.py
- test/test_frames.py
It looks to me like the `DataFrame` class has a small edge case issue in the way it computes `flow_controlled_length()` - if padding flag is set on the frame but padding length is zero, the 1 byte length field doesn't get accounted for.
> account for pad length field in flow control if zero valued

- docs/source/api.rst
- hyperframe/frame.py
- test/test_frames.py
This PR adds the ExtensionFrame object, which hyperframe can use to denote a frame whose identifier code isn't known to the package. This can be used in upstream consumers which do know the semantic meaning of that particular identifier code.
> Add ExtensionFrame object

- setup.py
Click the "Homepage" link on https://pypi.org/project/hyperframe/ takes you to the home of the hyper project itself, which doesn’t mention hyperframe at all.
> Provide a more useful link in setup.py

- .coveragerc
- .travis.yml
- Makefile
- hyperframe/flags.py
- setup.cfg
- setup.py
- test/test_frames.py
- test_requirements.txt
- tox.ini
* fix collections.abc deprecation: closes #123 
* bump dependencies for test requirements: closes #122
* add support for Python 3.7 and run tests against it
* run tests for pypy2 and pypy3 on Travis
* drop Python 3.3 support (basically impossible to test with modern CI systems and dependencies)
* adopt travis+tox+coveragerc architecture from other hyper projects
> Fix collections.abc deprecation, bump dependencies, drop py33 and pypy support

- docs/source/index.rst
Sample code needs to be updated because,,,
1. It is necessary to import `hyperframe.frame` instead of `hyperframe`.
2. `hyperframe.frame.Frame.parse_frame_header()` returns not only frame but also length.
3. `new_frame.parse_body()` accepts not `bytes` but `memoryview`.
closes #124
> Update sample code for #124

- hyperframe/frame.py
- test/test_frames.py
This parameter is introduced in RFC 8441 (Websockets over HTTP/2) and
assigned the 0x8 code
(http://www.iana.org/assignments/http2-parameters/http2-parameters.xhtml).
Support here allows for a future hyper-h2 support and onwards towards
a server that supports Websockets over HTTP/2.
> Add a new SETTINGS_ENABLE_CONNECT_PROTOCOL settings paramter

- .github/workflows/ci.yml
- .gitmodules
- HISTORY.rst
- hyperframe/frame.py
- test/test_external_collection.py
- test/test_frames.py
- tox.ini
fixes #68 
This PR runs the https://github.com/http2jp/http2-frame-test-case test cases as git-submodule with a small pytest wrapper to load them dynamically.
This PR fixes and actual serious bug with regard to padding in PUSH_PROMISE frames.
This PR contains various commits to fix individual bugs or test failures for frame parsing. Most of them are about increased input validation and more strict/correct interpretation of the RFC.
> run http2-frame-test-case test cases and fix padding

- HISTORY.rst
- hyperframe/frame.py
This fixes https://github.com/python-hyper/hyper-h2/issues/1231
> never raise ValueError - always use hyperframe custom types

- CHANGELOG.rst
- docs/source/api.rst
- src/hyperframe/exceptions.py
- src/hyperframe/frame.py
- test/test_frames.py
This PR restructures the hyperframe exception types.
* Introduce a new `HyperframeError` base class and use it for all custom exception (instead of `ValueError`).
* Split frame parsing errors from frame header or payload data errors: `InvalidFrameError` vs. `InvalidDataError`.
This fixes a regression in hyper-h2 which needs to differentiate between the error types to send the correct error code back to the other endpoint: https://github.com/python-hyper/hyper-h2/pull/1238
> use new exception type for data protocol errors

- CHANGELOG.rst
- MANIFEST.in
- Makefile
- setup.cfg
- setup.py
- src/hyperframe/frame.py
- tox.ini
ref https://github.com/python-hyper/wsproto/pull/157
> Repo layout
